//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

using Benner.Tecnologia.Business;
using Benner.Tecnologia.Common;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Linq;
using System.Reflection;
using System.Runtime.Serialization;
using System.Text;


namespace Patrus.Transportes.Treinamento.Vitor.Entities
{
    
    
    /// <summary>
    /// Interface para a tabela K_TRN_ALUGUEL_VITOR
    /// </summary>
    public partial interface IAluguel : IEntityBase
    {
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.1.0.20")]
        Patrus.Logistica.Compartilhado.Pessoas.Entities.IPessoa ClienteInstance
        {
            get;
            set;
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.1.0.20")]
        Handle ClienteHandle
        {
            get;
            set;
        }
        
        /// <summary>
        /// Data de alteracao (DATAALTERACAO.)
        /// Opcional = S, Invisível = False, Formato Data = Dia, Mês, Ano - Formato Hora = Hora, Minuto
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.1.0.20")]
        System.Nullable<System.DateTime> DataAlteracao
        {
            get;
            set;
        }
        
        /// <summary>
        /// Data aluguel (DATAALUGUEL.)
        /// Opcional = N, Invisível = False, Formato Data = Dia, Mês, Ano - Formato Hora = Hora, Minuto
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.1.0.20")]
        System.Nullable<System.DateTime> DataAluguel
        {
            get;
            set;
        }
        
        /// <summary>
        /// Data devolucao (DATADEVOLUCAO.)
        /// Opcional = S, Invisível = False, Formato Data = Dia, Mês, Ano - Formato Hora = Hora, Minuto
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.1.0.20")]
        System.Nullable<System.DateTime> DataDevolucao
        {
            get;
            set;
        }
        
        /// <summary>
        /// Data da inclusao (DATAINCLUSAO.)
        /// Opcional = N, Invisível = False, Formato Data = Dia, Mês, Ano - Formato Hora = Hora, Minuto
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.1.0.20")]
        System.Nullable<System.DateTime> DataInclusao
        {
            get;
            set;
        }
        
        /// <summary>
        /// Data prevista devol (DATAPREVISTADEVOL.)
        /// Opcional = S, Invisível = False, Formato Data = Dia, Mês, Ano - Formato Hora = Sem hora
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.1.0.20")]
        System.Nullable<System.DateTime> DataPrevistaDevol
        {
            get;
            set;
        }
        
        /// <summary>
        /// Pgto antecipado (PGTOANTECIPADO.)
        /// Opcional = N, Invisível = False, Default = False
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.1.0.20")]
        System.Nullable<bool> PgtoAntecipado
        {
            get;
            set;
        }
        
        /// <summary>
        /// Responsavel devolucao (RESPONSAVELDEVOLUCAO.)
        /// Opcional = S, Invisível = False, Tamanho = 30
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.1.0.20")]
        string ResponsavelDevolucao
        {
            get;
            set;
        }
        
        /// <summary>
        /// Situaçao (SITUACAO.)
        /// Opcional = N, Invisível = False
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.1.0.20")]
        AluguelSituacaoListaItens Situacao
        {
            get;
            set;
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.1.0.20")]
        Benner.Corporativo.Definicoes.Administracao.IZGrupoUsuarios UsuarioAlteracaoInstance
        {
            get;
            set;
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.1.0.20")]
        Handle UsuarioAlteracaoHandle
        {
            get;
            set;
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.1.0.20")]
        Benner.Corporativo.Definicoes.Administracao.IZGrupoUsuarios UsuarioInclusaoInstance
        {
            get;
            set;
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.1.0.20")]
        Handle UsuarioInclusaoHandle
        {
            get;
            set;
        }
        
        /// <summary>
        /// Valor final (VALORFINAL.)
        /// Opcional = S, Invisível = False, Valor Mínimo = , Valor Máximo = , Tipo no Builder = Número
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.1.0.20")]
        System.Nullable<decimal> ValorFinal
        {
            get;
            set;
        }
        
        /// <summary>
        /// Valor inicial (VALORINICIAL.)
        /// Opcional = S, Invisível = False, Valor Mínimo = , Valor Máximo = , Tipo no Builder = Número
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.1.0.20")]
        System.Nullable<decimal> ValorInicial
        {
            get;
            set;
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.1.0.20")]
        Patrus.Transportes.Treinamento.Vitor.Entities.IVeiculo VeiculoInstance
        {
            get;
            set;
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.1.0.20")]
        Handle VeiculoHandle
        {
            get;
            set;
        }
    }
    
    /// <summary>
    /// Interface para o DAO para a tabela K_TRN_ALUGUEL_VITOR
    /// </summary>
    public partial interface IAluguelDao : IBusinessEntityDao<IAluguel>
    {
    }
    
    /// <summary>
    /// DAO para a tabela K_TRN_ALUGUEL_VITOR
    /// </summary>
    public partial class AluguelDao : BusinessEntityDao<Aluguel, IAluguel>, IAluguelDao
    {
        
        public static AluguelDao CreateInstance()
        {
            return CreateInstance<AluguelDao>();
        }
    }
    
    /// <summary>
    /// Esta classe contém os itens do campo SITUACAO.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.1.0.20")]
    public class AluguelSituacaoListaItens : ListItems<AluguelSituacaoListaItens>
    {
        
        /// <summary>
        /// Valor = 1, Item = Reservado.
        /// </summary>
        public static AluguelSituacaoListaItens ItemReservado;
        
        /// <summary>
        /// Valor = 2, Item = Alugado.
        /// </summary>
        public static AluguelSituacaoListaItens ItemAlugado;
        
        /// <summary>
        /// Valor = 3, Item = Finalizado.
        /// </summary>
        public static AluguelSituacaoListaItens ItemFinalizado;
        
		public static implicit operator AluguelSituacaoListaItens(int index)
		{
			return GetByIndex(index);
		}

		public static implicit operator int(AluguelSituacaoListaItens item)
		{
			return item.Index;
		}
        
        static AluguelSituacaoListaItens()
        {
			ItemReservado = new AluguelSituacaoListaItens {Index = 1, Description ="Reservado"};
			ItemAlugado = new AluguelSituacaoListaItens {Index = 2, Description ="Alugado"};
			ItemFinalizado = new AluguelSituacaoListaItens {Index = 3, Description ="Finalizado"};

			Items.Add(ItemReservado);
			Items.Add(ItemAlugado);
			Items.Add(ItemFinalizado);

        }
    }
    
    /// <summary>
    /// Aluguel
    /// </summary>
    [EntityDefinitionName("K_TRN_ALUGUEL_VITOR")]
    [DataContract(Namespace = "http://Benner.Tecnologia.Common.DataContracts/2007/09", Name = "EntityBase")]
    public partial class Aluguel : BusinessEntity<Aluguel>, IAluguel
    {
        
        /// <summary>
        /// Possui constantes para retornarem o nome dos campos definidos no Builder para cada propriedade
        /// </summary>
		public static class FieldNames
		{
			public const string Alugar = "ALUGAR";
			public const string Cliente = "CLIENTE";
			public const string DataAlteracao = "DATAALTERACAO";
			public const string DataAluguel = "DATAALUGUEL";
			public const string DataDevolucao = "DATADEVOLUCAO";
			public const string DataInclusao = "DATAINCLUSAO";
			public const string DataPrevistaDevol = "DATAPREVISTADEVOL";
			public const string GRUPODADOSALUG = "GRUPODADOSALUG";
			public const string PgtoAntecipado = "PGTOANTECIPADO";
			public const string ResponsavelDevolucao = "RESPONSAVELDEVOLUCAO";
			public const string Situacao = "SITUACAO";
			public const string UsuarioAlteracao = "USUARIOALTERACAO";
			public const string UsuarioInclusao = "USUARIOINCLUSAO";
			public const string ValorFinal = "VALORFINAL";
			public const string ValorInicial = "VALORINICIAL";
			public const string Veiculo = "VEICULO";
		}

        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.1.0.20")]
        public Patrus.Logistica.Compartilhado.Pessoas.Entities.IPessoa ClienteInstance
        {
            get
            {
                if (Cliente.Handle == null)
                {
					return null;
                }
                return Cliente.Instance;
            }
            set
            {
                if (value == null)
                {
					Cliente = null;
					return;
                }
                Cliente.Instance = (Patrus.Logistica.Compartilhado.Pessoas.Entities.Pessoa) value;
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.1.0.20")]
        public Handle ClienteHandle
        {
            get
            {
                return Cliente.Handle;
            }
            set
            {
                Cliente.Handle = value;
            }
        }
        
        /// <summary>
        /// Cliente (CLIENTE.)
        /// Opcional = N, Invisível = False, Pesquisar = GN_PESSOAS
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.1.0.20")]
        public Benner.Tecnologia.Common.EntityAssociation<Patrus.Logistica.Compartilhado.Pessoas.Entities.Pessoa> Cliente
        {
            get
            {
                return (Fields["CLIENTE"] as EntityAssociation).Wrap<Patrus.Logistica.Compartilhado.Pessoas.Entities.Pessoa>(Patrus.Logistica.Compartilhado.Pessoas.Entities.Pessoa.Get);
            }
            set
            {
                if (value == null)
                {
                    this.Cliente.Handle = null;
                }
                else
                {
                    if (value.Association.IsLoaded)
                    {
                        this.Cliente.Instance = value.Instance;
                    }
                    else
                    {
                        this.Cliente.Handle = value.Handle;
                    }
                }
            }
        }
        
        /// <summary>
        /// Data de alteracao (DATAALTERACAO.)
        /// Opcional = S, Invisível = False, Formato Data = Dia, Mês, Ano - Formato Hora = Hora, Minuto
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.1.0.20")]
        public System.Nullable<System.DateTime> DataAlteracao
        {
            get
            {
                return Fields["DATAALTERACAO"] as System.Nullable<System.DateTime>;
            }
            set
            {
                Fields["DATAALTERACAO"] = value;
            }
        }
        
        /// <summary>
        /// Data aluguel (DATAALUGUEL.)
        /// Opcional = N, Invisível = False, Formato Data = Dia, Mês, Ano - Formato Hora = Hora, Minuto
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.1.0.20")]
        public System.Nullable<System.DateTime> DataAluguel
        {
            get
            {
                return Fields["DATAALUGUEL"] as System.Nullable<System.DateTime>;
            }
            set
            {
                Fields["DATAALUGUEL"] = value;
            }
        }
        
        /// <summary>
        /// Data devolucao (DATADEVOLUCAO.)
        /// Opcional = S, Invisível = False, Formato Data = Dia, Mês, Ano - Formato Hora = Hora, Minuto
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.1.0.20")]
        public System.Nullable<System.DateTime> DataDevolucao
        {
            get
            {
                return Fields["DATADEVOLUCAO"] as System.Nullable<System.DateTime>;
            }
            set
            {
                Fields["DATADEVOLUCAO"] = value;
            }
        }
        
        /// <summary>
        /// Data da inclusao (DATAINCLUSAO.)
        /// Opcional = N, Invisível = False, Formato Data = Dia, Mês, Ano - Formato Hora = Hora, Minuto
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.1.0.20")]
        public System.Nullable<System.DateTime> DataInclusao
        {
            get
            {
                return Fields["DATAINCLUSAO"] as System.Nullable<System.DateTime>;
            }
            set
            {
                Fields["DATAINCLUSAO"] = value;
            }
        }
        
        /// <summary>
        /// Data prevista devol (DATAPREVISTADEVOL.)
        /// Opcional = S, Invisível = False, Formato Data = Dia, Mês, Ano - Formato Hora = Sem hora
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.1.0.20")]
        public System.Nullable<System.DateTime> DataPrevistaDevol
        {
            get
            {
                return Fields["DATAPREVISTADEVOL"] as System.Nullable<System.DateTime>;
            }
            set
            {
                Fields["DATAPREVISTADEVOL"] = value;
            }
        }
        
        /// <summary>
        /// Pgto antecipado (PGTOANTECIPADO.)
        /// Opcional = N, Invisível = False, Default = False
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.1.0.20")]
        public System.Nullable<bool> PgtoAntecipado
        {
            get
            {
                return Fields["PGTOANTECIPADO"] as System.Nullable<System.Boolean>;
            }
            set
            {
                Fields["PGTOANTECIPADO"] = value;
            }
        }
        
        /// <summary>
        /// Responsavel devolucao (RESPONSAVELDEVOLUCAO.)
        /// Opcional = S, Invisível = False, Tamanho = 30
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.1.0.20")]
        public string ResponsavelDevolucao
        {
            get
            {
                return Fields["RESPONSAVELDEVOLUCAO"] as System.String;
            }
            set
            {
                Fields["RESPONSAVELDEVOLUCAO"] = value;
            }
        }
        
        /// <summary>
        /// Situaçao (SITUACAO.)
        /// Opcional = N, Invisível = False
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.1.0.20")]
        public AluguelSituacaoListaItens Situacao
        {
            get
            {
                ListItem listItem = Fields["SITUACAO"] as ListItem;
				if (listItem != null)
					return new AluguelSituacaoListaItens { Index = listItem.Value, Description = listItem.Text };
				return null;
            }
            set
            {
                if (value != null)
					Fields["SITUACAO"] = new ListItem(value.Index, value.Description);
				else
					Fields["SITUACAO"] = null;
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.1.0.20")]
        public Benner.Corporativo.Definicoes.Administracao.IZGrupoUsuarios UsuarioAlteracaoInstance
        {
            get
            {
                if (UsuarioAlteracao.Handle == null)
                {
					return null;
                }
                return UsuarioAlteracao.Instance;
            }
            set
            {
                if (value == null)
                {
					UsuarioAlteracao = null;
					return;
                }
                UsuarioAlteracao.Instance = (Benner.Corporativo.Definicoes.Administracao.ZGrupoUsuarios) value;
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.1.0.20")]
        public Handle UsuarioAlteracaoHandle
        {
            get
            {
                return UsuarioAlteracao.Handle;
            }
            set
            {
                UsuarioAlteracao.Handle = value;
            }
        }
        
        /// <summary>
        /// Usuario de alteracao (USUARIOALTERACAO.)
        /// Opcional = S, Invisível = False, Pesquisar = Z_GRUPOUSUARIOS
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.1.0.20")]
        public Benner.Tecnologia.Common.EntityAssociation<Benner.Corporativo.Definicoes.Administracao.ZGrupoUsuarios> UsuarioAlteracao
        {
            get
            {
                return (Fields["USUARIOALTERACAO"] as EntityAssociation).Wrap<Benner.Corporativo.Definicoes.Administracao.ZGrupoUsuarios>(Benner.Corporativo.Definicoes.Administracao.ZGrupoUsuarios.Get);
            }
            set
            {
                if (value == null)
                {
                    this.UsuarioAlteracao.Handle = null;
                }
                else
                {
                    if (value.Association.IsLoaded)
                    {
                        this.UsuarioAlteracao.Instance = value.Instance;
                    }
                    else
                    {
                        this.UsuarioAlteracao.Handle = value.Handle;
                    }
                }
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.1.0.20")]
        public Benner.Corporativo.Definicoes.Administracao.IZGrupoUsuarios UsuarioInclusaoInstance
        {
            get
            {
                if (UsuarioInclusao.Handle == null)
                {
					return null;
                }
                return UsuarioInclusao.Instance;
            }
            set
            {
                if (value == null)
                {
					UsuarioInclusao = null;
					return;
                }
                UsuarioInclusao.Instance = (Benner.Corporativo.Definicoes.Administracao.ZGrupoUsuarios) value;
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.1.0.20")]
        public Handle UsuarioInclusaoHandle
        {
            get
            {
                return UsuarioInclusao.Handle;
            }
            set
            {
                UsuarioInclusao.Handle = value;
            }
        }
        
        /// <summary>
        /// Usuário Inclusão (USUARIOINCLUSAO.)
        /// Opcional = N, Invisível = False, Pesquisar = Z_GRUPOUSUARIOS
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.1.0.20")]
        public Benner.Tecnologia.Common.EntityAssociation<Benner.Corporativo.Definicoes.Administracao.ZGrupoUsuarios> UsuarioInclusao
        {
            get
            {
                return (Fields["USUARIOINCLUSAO"] as EntityAssociation).Wrap<Benner.Corporativo.Definicoes.Administracao.ZGrupoUsuarios>(Benner.Corporativo.Definicoes.Administracao.ZGrupoUsuarios.Get);
            }
            set
            {
                if (value == null)
                {
                    this.UsuarioInclusao.Handle = null;
                }
                else
                {
                    if (value.Association.IsLoaded)
                    {
                        this.UsuarioInclusao.Instance = value.Instance;
                    }
                    else
                    {
                        this.UsuarioInclusao.Handle = value.Handle;
                    }
                }
            }
        }
        
        /// <summary>
        /// Valor final (VALORFINAL.)
        /// Opcional = S, Invisível = False, Valor Mínimo = , Valor Máximo = , Tipo no Builder = Número
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.1.0.20")]
        public System.Nullable<decimal> ValorFinal
        {
            get
            {
                return Fields["VALORFINAL"] as System.Nullable<System.Decimal>;
            }
            set
            {
                Fields["VALORFINAL"] = value;
            }
        }
        
        /// <summary>
        /// Valor inicial (VALORINICIAL.)
        /// Opcional = S, Invisível = False, Valor Mínimo = , Valor Máximo = , Tipo no Builder = Número
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.1.0.20")]
        public System.Nullable<decimal> ValorInicial
        {
            get
            {
                return Fields["VALORINICIAL"] as System.Nullable<System.Decimal>;
            }
            set
            {
                Fields["VALORINICIAL"] = value;
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.1.0.20")]
        public Patrus.Transportes.Treinamento.Vitor.Entities.IVeiculo VeiculoInstance
        {
            get
            {
                if (Veiculo.Handle == null)
                {
					return null;
                }
                return Veiculo.Instance;
            }
            set
            {
                if (value == null)
                {
					Veiculo = null;
					return;
                }
                Veiculo.Instance = (Patrus.Transportes.Treinamento.Vitor.Entities.Veiculo) value;
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.1.0.20")]
        public Handle VeiculoHandle
        {
            get
            {
                return Veiculo.Handle;
            }
            set
            {
                Veiculo.Handle = value;
            }
        }
        
        /// <summary>
        /// Veiculo (VEICULO.)
        /// Opcional = N, Invisível = False, Pesquisar = K_TRN_VITOR_VEICULOS
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.1.0.20")]
        public Benner.Tecnologia.Common.EntityAssociation<Patrus.Transportes.Treinamento.Vitor.Entities.Veiculo> Veiculo
        {
            get
            {
                return (Fields["VEICULO"] as EntityAssociation).Wrap<Patrus.Transportes.Treinamento.Vitor.Entities.Veiculo>(Patrus.Transportes.Treinamento.Vitor.Entities.Veiculo.Get);
            }
            set
            {
                if (value == null)
                {
                    this.Veiculo.Handle = null;
                }
                else
                {
                    if (value.Association.IsLoaded)
                    {
                        this.Veiculo.Instance = value.Instance;
                    }
                    else
                    {
                        this.Veiculo.Handle = value.Handle;
                    }
                }
            }
        }
    }
}
