//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

using Benner.Tecnologia.Business;
using Benner.Tecnologia.Common;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Linq;
using System.Reflection;
using System.Runtime.Serialization;
using System.Text;


namespace Patrus.Transportes.Treinamento.Vitor.Entities
{
    
    
    /// <summary>
    /// Interface para a tabela K_TRN_MODELOSV_VITOR
    /// </summary>
    public partial interface IModelosvVitor : IEntityBase
    {
        
        /// <summary>
        /// Ano primeiro modelo (ANOMODELO.)
        /// Opcional = S, Invisível = False, Valor Mínimo = 2200, Valor Máximo = , Tipo do Builder = Inteiro
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.1.0.20")]
        System.Nullable<long> Ano_Modelo
        {
            get;
            set;
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.1.0.20")]
        Benner.Tecnologia.Common.IEntityBase MarcaInstance
        {
            get;
            set;
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.1.0.20")]
        Handle MarcaHandle
        {
            get;
            set;
        }
        
        /// <summary>
        /// Nome modelo (NOME.)
        /// Opcional = N, Invisível = False, Tamanho = 50
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.1.0.20")]
        string Nome
        {
            get;
            set;
        }
        
        /// <summary>
        /// Valor sugerido diaria (VALORSUGERIDODIARIA.)
        /// Opcional = S, Invisível = False, Valor Mínimo = 9999, Valor Máximo = , Tipo no Builder = Número
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.1.0.20")]
        System.Nullable<decimal> Valor_Sugerido_Diaria
        {
            get;
            set;
        }
    }
    
    /// <summary>
    /// Interface para o DAO para a tabela K_TRN_MODELOSV_VITOR
    /// </summary>
    public partial interface IModelosvVitorDao : IBusinessEntityDao<IModelosvVitor>
    {
    }
    
    /// <summary>
    /// DAO para a tabela K_TRN_MODELOSV_VITOR
    /// </summary>
    public partial class ModelosvVitorDao : BusinessEntityDao<ModelosvVitor, IModelosvVitor>, IModelosvVitorDao
    {
        
        public static ModelosvVitorDao CreateInstance()
        {
            return CreateInstance<ModelosvVitorDao>();
        }
    }
    
    /// <summary>
    /// ModelosvVitor
    /// </summary>
    [EntityDefinitionName("K_TRN_MODELOSV_VITOR")]
    [DataContract(Namespace = "http://Benner.Tecnologia.Common.DataContracts/2007/09", Name = "EntityBase")]
    public partial class ModelosvVitor : BusinessEntity<ModelosvVitor>, IModelosvVitor
    {
        
        /// <summary>
        /// Possui constantes para retornarem o nome dos campos definidos no Builder para cada propriedade
        /// </summary>
		public static class FieldNames
		{
			public const string Ano_Modelo = "ANOMODELO";
			public const string Marca = "MARCA";
			public const string Nome = "NOME";
			public const string Valor_Sugerido_Diaria = "VALORSUGERIDODIARIA";
		}

        
        /// <summary>
        /// Ano primeiro modelo (ANOMODELO.)
        /// Opcional = S, Invisível = False, Valor Mínimo = 2200, Valor Máximo = , Tipo do Builder = Inteiro
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.1.0.20")]
        public System.Nullable<long> Ano_Modelo
        {
            get
            {
                return Fields["ANOMODELO"] as System.Nullable<System.Int64>;
            }
            set
            {
                Fields["ANOMODELO"] = value;
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.1.0.20")]
        public Benner.Tecnologia.Common.IEntityBase MarcaInstance
        {
            get
            {
                if (Marca.Handle == null)
                {
					return null;
                }
                return Marca.Instance;
            }
            set
            {
                if (value == null)
                {
					Marca = null;
					return;
                }
                Marca.Instance = (EntityBase) value;
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.1.0.20")]
        public Handle MarcaHandle
        {
            get
            {
                return Marca.Handle;
            }
            set
            {
                Marca.Handle = value;
            }
        }
        
        /// <summary>
        /// Marca (MARCA.)
        /// Opcional = N, Invisível = False, Pesquisar = K_TRN_MARCAS_VITOR
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.1.0.20")]
        public Benner.Tecnologia.Common.EntityAssociation Marca
        {
            get
            {
                return Fields["MARCA"] as Benner.Tecnologia.Common.EntityAssociation;
            }
            set
            {
                if (value == null)
                {
                    this.Marca.Handle = null;
                }
                else
                {
                    if (value.IsLoaded)
                    {
                        this.Marca.Instance = value.Instance;
                    }
                    else
                    {
                        this.Marca.Handle = value.Handle;
                    }
                }
            }
        }
        
        /// <summary>
        /// Nome modelo (NOME.)
        /// Opcional = N, Invisível = False, Tamanho = 50
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.1.0.20")]
        public string Nome
        {
            get
            {
                return Fields["NOME"] as System.String;
            }
            set
            {
                Fields["NOME"] = value;
            }
        }
        
        /// <summary>
        /// Valor sugerido diaria (VALORSUGERIDODIARIA.)
        /// Opcional = S, Invisível = False, Valor Mínimo = 9999, Valor Máximo = , Tipo no Builder = Número
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.1.0.20")]
        public System.Nullable<decimal> Valor_Sugerido_Diaria
        {
            get
            {
                return Fields["VALORSUGERIDODIARIA"] as System.Nullable<System.Decimal>;
            }
            set
            {
                Fields["VALORSUGERIDODIARIA"] = value;
            }
        }
    }
}
