//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

using Benner.Tecnologia.Business;
using Benner.Tecnologia.Common;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Linq;
using System.Reflection;
using System.Runtime.Serialization;
using System.Text;


namespace Patrus.Transportes.Treinamento.Vitor.Entities
{
    
    
    /// <summary>
    /// Interface para a tabela K_TRN_VITOR_VEICULOS
    /// </summary>
    public partial interface IVeiculo : IEntityBase
    {
        
        /// <summary>
        /// Ano (ANO.)
        /// Opcional = N, Invisível = False, Valor Mínimo = 2200, Valor Máximo = , Tipo do Builder = Inteiro
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.1.0.20")]
        System.Nullable<long> Ano
        {
            get;
            set;
        }
        
        /// <summary>
        /// Dataaquisicao (DATAAQUISICAO.)
        /// Opcional = S, Invisível = False, Formato Data = Dia, Mês, Ano - Formato Hora = Sem hora
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.1.0.20")]
        System.Nullable<System.DateTime> DataAquisicao
        {
            get;
            set;
        }
        
        /// <summary>
        /// Data fim (DATAFIM.)
        /// Opcional = S, Invisível = False, Formato Data = Dia, Mês, Ano - Formato Hora = Sem hora
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.1.0.20")]
        System.Nullable<System.DateTime> DataFim
        {
            get;
            set;
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.1.0.20")]
        Benner.Corporativo.Definicoes.Administracao.IEstados EstadoPlacaInstance
        {
            get;
            set;
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.1.0.20")]
        Handle EstadoPlacaHandle
        {
            get;
            set;
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.1.0.20")]
        Patrus.Logistica.Compartilhado.Pessoas.Entities.IPessoa FornecedorInstance
        {
            get;
            set;
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.1.0.20")]
        Handle FornecedorHandle
        {
            get;
            set;
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.1.0.20")]
        Benner.Tecnologia.Common.IEntityBase MarcadInstance
        {
            get;
            set;
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.1.0.20")]
        Handle MarcadHandle
        {
            get;
            set;
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.1.0.20")]
        Benner.Tecnologia.Common.IEntityBase ModelocadInstance
        {
            get;
            set;
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.1.0.20")]
        Handle ModelocadHandle
        {
            get;
            set;
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.1.0.20")]
        Benner.Corporativo.Definicoes.Administracao.IMunicipios MunicipioInstance
        {
            get;
            set;
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.1.0.20")]
        Handle MunicipioHandle
        {
            get;
            set;
        }
        
        /// <summary>
        /// Placa (PLACA.)
        /// Opcional = N, Invisível = False, Tamanho = 7
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.1.0.20")]
        string Placa
        {
            get;
            set;
        }
        
        /// <summary>
        /// Tipo (TIPO.)
        /// Opcional = N, Invisível = False
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.1.0.20")]
        VeiculoTipoTabItens Tipo
        {
            get;
            set;
        }
        
        /// <summary>
        /// Valor aquisicao (VALORAQUISICAO.)
        /// Opcional = S, Invisível = False, Valor Mínimo = , Valor Máximo = , Tipo no Builder = Número
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.1.0.20")]
        System.Nullable<decimal> ValorAquisicao
        {
            get;
            set;
        }
        
        /// <summary>
        /// Valordiaria (VALORDIARIA.)
        /// Opcional = N, Invisível = False, Valor Mínimo = 9999999, Valor Máximo = , Tipo no Builder = Número
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.1.0.20")]
        System.Nullable<decimal> ValorDiaria
        {
            get;
            set;
        }
    }
    
    /// <summary>
    /// Interface para o DAO para a tabela K_TRN_VITOR_VEICULOS
    /// </summary>
    public partial interface IVeiculoDao : IBusinessEntityDao<IVeiculo>
    {
    }
    
    /// <summary>
    /// DAO para a tabela K_TRN_VITOR_VEICULOS
    /// </summary>
    public partial class VeiculoDao : BusinessEntityDao<Veiculo, IVeiculo>, IVeiculoDao
    {
        
        public static VeiculoDao CreateInstance()
        {
            return CreateInstance<VeiculoDao>();
        }
    }
    
    /// <summary>
    /// Esta classe contém os itens do campo TIPO.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.1.0.20")]
    public class VeiculoTipoTabItens : TabItems<VeiculoTipoTabItens>
    {
        
        /// <summary>
        /// Valor = 1, Item = Proprio.
        /// </summary>
        public static VeiculoTipoTabItens ItemProprio;
        
        /// <summary>
        /// Valor = 2, Item = Terceiro.
        /// </summary>
        public static VeiculoTipoTabItens ItemTerceiro;
        
		public static implicit operator VeiculoTipoTabItens(int index)
		{
			return GetByIndex(index);
		}

		public static implicit operator int(VeiculoTipoTabItens item)
		{
			return item.Index;
		}
        
        static VeiculoTipoTabItens()
        {
			ItemProprio = new VeiculoTipoTabItens {Index = 1, Description ="Proprio"};
			ItemTerceiro = new VeiculoTipoTabItens {Index = 2, Description ="Terceiro"};

			Items.Add(ItemProprio);
			Items.Add(ItemTerceiro);

        }
    }
    
    /// <summary>
    /// Veiculo
    /// </summary>
    [EntityDefinitionName("K_TRN_VITOR_VEICULOS")]
    [DataContract(Namespace = "http://Benner.Tecnologia.Common.DataContracts/2007/09", Name = "EntityBase")]
    public partial class Veiculo : BusinessEntity<Veiculo>, IVeiculo
    {
        
        /// <summary>
        /// Possui constantes para retornarem o nome dos campos definidos no Builder para cada propriedade
        /// </summary>
		public static class FieldNames
		{
			public const string Ano = "ANO";
			public const string DataAquisicao = "DATAAQUISICAO";
			public const string DataFim = "DATAFIM";
			public const string EstadoPlaca = "ESTADOPLACA";
			public const string Fornecedor = "FORNECEDOR";
			public const string GRUPOVEICULO = "GRUPOVEICULO";
			public const string MARCA = "MARCA";
			public const string Marcad = "MARCAD";
			public const string Modelo = "MODELO";
			public const string Modelocad = "MODELOCAD";
			public const string Municipio = "MUNICIPIO";
			public const string Placa = "PLACA";
			public const string Tipo = "TIPO";
			public const string ValorAquisicao = "VALORAQUISICAO";
			public const string ValorDiaria = "VALORDIARIA";
		}

        
        /// <summary>
        /// Ano (ANO.)
        /// Opcional = N, Invisível = False, Valor Mínimo = 2200, Valor Máximo = , Tipo do Builder = Inteiro
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.1.0.20")]
        public System.Nullable<long> Ano
        {
            get
            {
                return Fields["ANO"] as System.Nullable<System.Int64>;
            }
            set
            {
                Fields["ANO"] = value;
            }
        }
        
        /// <summary>
        /// Dataaquisicao (DATAAQUISICAO.)
        /// Opcional = S, Invisível = False, Formato Data = Dia, Mês, Ano - Formato Hora = Sem hora
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.1.0.20")]
        public System.Nullable<System.DateTime> DataAquisicao
        {
            get
            {
                return Fields["DATAAQUISICAO"] as System.Nullable<System.DateTime>;
            }
            set
            {
                Fields["DATAAQUISICAO"] = value;
            }
        }
        
        /// <summary>
        /// Data fim (DATAFIM.)
        /// Opcional = S, Invisível = False, Formato Data = Dia, Mês, Ano - Formato Hora = Sem hora
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.1.0.20")]
        public System.Nullable<System.DateTime> DataFim
        {
            get
            {
                return Fields["DATAFIM"] as System.Nullable<System.DateTime>;
            }
            set
            {
                Fields["DATAFIM"] = value;
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.1.0.20")]
        public Benner.Corporativo.Definicoes.Administracao.IEstados EstadoPlacaInstance
        {
            get
            {
                if (EstadoPlaca.Handle == null)
                {
					return null;
                }
                return EstadoPlaca.Instance;
            }
            set
            {
                if (value == null)
                {
					EstadoPlaca = null;
					return;
                }
                EstadoPlaca.Instance = (Benner.Corporativo.Definicoes.Administracao.Estados) value;
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.1.0.20")]
        public Handle EstadoPlacaHandle
        {
            get
            {
                return EstadoPlaca.Handle;
            }
            set
            {
                EstadoPlaca.Handle = value;
            }
        }
        
        /// <summary>
        /// Estado placa (ESTADOPLACA.)
        /// Opcional = N, Invisível = False, Pesquisar = ESTADOS
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.1.0.20")]
        public Benner.Tecnologia.Common.EntityAssociation<Benner.Corporativo.Definicoes.Administracao.Estados> EstadoPlaca
        {
            get
            {
                return (Fields["ESTADOPLACA"] as EntityAssociation).Wrap<Benner.Corporativo.Definicoes.Administracao.Estados>(Benner.Corporativo.Definicoes.Administracao.Estados.Get);
            }
            set
            {
                if (value == null)
                {
                    this.EstadoPlaca.Handle = null;
                }
                else
                {
                    if (value.Association.IsLoaded)
                    {
                        this.EstadoPlaca.Instance = value.Instance;
                    }
                    else
                    {
                        this.EstadoPlaca.Handle = value.Handle;
                    }
                }
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.1.0.20")]
        public Patrus.Logistica.Compartilhado.Pessoas.Entities.IPessoa FornecedorInstance
        {
            get
            {
                if (Fornecedor.Handle == null)
                {
					return null;
                }
                return Fornecedor.Instance;
            }
            set
            {
                if (value == null)
                {
					Fornecedor = null;
					return;
                }
                Fornecedor.Instance = (Patrus.Logistica.Compartilhado.Pessoas.Entities.Pessoa) value;
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.1.0.20")]
        public Handle FornecedorHandle
        {
            get
            {
                return Fornecedor.Handle;
            }
            set
            {
                Fornecedor.Handle = value;
            }
        }
        
        /// <summary>
        /// Fornecedor (FORNECEDOR.)
        /// Opcional = S, Invisível = False, Pesquisar = GN_PESSOAS
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.1.0.20")]
        public Benner.Tecnologia.Common.EntityAssociation<Patrus.Logistica.Compartilhado.Pessoas.Entities.Pessoa> Fornecedor
        {
            get
            {
                return (Fields["FORNECEDOR"] as EntityAssociation).Wrap<Patrus.Logistica.Compartilhado.Pessoas.Entities.Pessoa>(Patrus.Logistica.Compartilhado.Pessoas.Entities.Pessoa.Get);
            }
            set
            {
                if (value == null)
                {
                    this.Fornecedor.Handle = null;
                }
                else
                {
                    if (value.Association.IsLoaded)
                    {
                        this.Fornecedor.Instance = value.Instance;
                    }
                    else
                    {
                        this.Fornecedor.Handle = value.Handle;
                    }
                }
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.1.0.20")]
        public Benner.Tecnologia.Common.IEntityBase MarcadInstance
        {
            get
            {
                if (Marcad.Handle == null)
                {
					return null;
                }
                return Marcad.Instance;
            }
            set
            {
                if (value == null)
                {
					Marcad = null;
					return;
                }
                Marcad.Instance = (EntityBase) value;
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.1.0.20")]
        public Handle MarcadHandle
        {
            get
            {
                return Marcad.Handle;
            }
            set
            {
                Marcad.Handle = value;
            }
        }
        
        /// <summary>
        /// Marca (MARCAD.)
        /// Opcional = S, Invisível = False, Pesquisar = K_TRN_MARCAS_VITOR
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.1.0.20")]
        public Benner.Tecnologia.Common.EntityAssociation Marcad
        {
            get
            {
                return Fields["MARCAD"] as Benner.Tecnologia.Common.EntityAssociation;
            }
            set
            {
                if (value == null)
                {
                    this.Marcad.Handle = null;
                }
                else
                {
                    if (value.IsLoaded)
                    {
                        this.Marcad.Instance = value.Instance;
                    }
                    else
                    {
                        this.Marcad.Handle = value.Handle;
                    }
                }
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.1.0.20")]
        public Benner.Tecnologia.Common.IEntityBase ModelocadInstance
        {
            get
            {
                if (Modelocad.Handle == null)
                {
					return null;
                }
                return Modelocad.Instance;
            }
            set
            {
                if (value == null)
                {
					Modelocad = null;
					return;
                }
                Modelocad.Instance = (EntityBase) value;
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.1.0.20")]
        public Handle ModelocadHandle
        {
            get
            {
                return Modelocad.Handle;
            }
            set
            {
                Modelocad.Handle = value;
            }
        }
        
        /// <summary>
        /// Modelo (MODELOCAD.)
        /// Opcional = N, Invisível = False, Pesquisar = K_TRN_MODELOSV_VITOR
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.1.0.20")]
        public Benner.Tecnologia.Common.EntityAssociation Modelocad
        {
            get
            {
                return Fields["MODELOCAD"] as Benner.Tecnologia.Common.EntityAssociation;
            }
            set
            {
                if (value == null)
                {
                    this.Modelocad.Handle = null;
                }
                else
                {
                    if (value.IsLoaded)
                    {
                        this.Modelocad.Instance = value.Instance;
                    }
                    else
                    {
                        this.Modelocad.Handle = value.Handle;
                    }
                }
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.1.0.20")]
        public Benner.Corporativo.Definicoes.Administracao.IMunicipios MunicipioInstance
        {
            get
            {
                if (Municipio.Handle == null)
                {
					return null;
                }
                return Municipio.Instance;
            }
            set
            {
                if (value == null)
                {
					Municipio = null;
					return;
                }
                Municipio.Instance = (Benner.Corporativo.Definicoes.Administracao.Municipios) value;
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.1.0.20")]
        public Handle MunicipioHandle
        {
            get
            {
                return Municipio.Handle;
            }
            set
            {
                Municipio.Handle = value;
            }
        }
        
        /// <summary>
        /// Municipio (MUNICIPIO.)
        /// Opcional = N, Invisível = False, Pesquisar = MUNICIPIOS
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.1.0.20")]
        public Benner.Tecnologia.Common.EntityAssociation<Benner.Corporativo.Definicoes.Administracao.Municipios> Municipio
        {
            get
            {
                return (Fields["MUNICIPIO"] as EntityAssociation).Wrap<Benner.Corporativo.Definicoes.Administracao.Municipios>(Benner.Corporativo.Definicoes.Administracao.Municipios.Get);
            }
            set
            {
                if (value == null)
                {
                    this.Municipio.Handle = null;
                }
                else
                {
                    if (value.Association.IsLoaded)
                    {
                        this.Municipio.Instance = value.Instance;
                    }
                    else
                    {
                        this.Municipio.Handle = value.Handle;
                    }
                }
            }
        }
        
        /// <summary>
        /// Placa (PLACA.)
        /// Opcional = N, Invisível = False, Tamanho = 7
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.1.0.20")]
        public string Placa
        {
            get
            {
                return Fields["PLACA"] as System.String;
            }
            set
            {
                Fields["PLACA"] = value;
            }
        }
        
        /// <summary>
        /// Tipo (TIPO.)
        /// Opcional = N, Invisível = False
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.1.0.20")]
        public VeiculoTipoTabItens Tipo
        {
            get
            {
                TabItem tabItem = Fields["TIPO"] as TabItem;
				if (tabItem != null)
					return new VeiculoTipoTabItens { Index = tabItem.Value, Description = tabItem.Text };
				return null;
            }
            set
            {
                if (value != null)
					Fields["TIPO"] = new TabItem(value.Index, value.Description);
				else
					Fields["TIPO"] = null;
            }
        }
        
        /// <summary>
        /// Valor aquisicao (VALORAQUISICAO.)
        /// Opcional = S, Invisível = False, Valor Mínimo = , Valor Máximo = , Tipo no Builder = Número
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.1.0.20")]
        public System.Nullable<decimal> ValorAquisicao
        {
            get
            {
                return Fields["VALORAQUISICAO"] as System.Nullable<System.Decimal>;
            }
            set
            {
                Fields["VALORAQUISICAO"] = value;
            }
        }
        
        /// <summary>
        /// Valordiaria (VALORDIARIA.)
        /// Opcional = N, Invisível = False, Valor Mínimo = 9999999, Valor Máximo = , Tipo no Builder = Número
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.1.0.20")]
        public System.Nullable<decimal> ValorDiaria
        {
            get
            {
                return Fields["VALORDIARIA"] as System.Nullable<System.Decimal>;
            }
            set
            {
                Fields["VALORDIARIA"] = value;
            }
        }
    }
}
