//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

using Benner.Tecnologia.Business;
using Benner.Tecnologia.Common;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Linq;
using System.Reflection;
using System.Runtime.Serialization;
using System.Text;


namespace Patrus.Transportes.Treinamento.Vitor.VirtualTables
{
    
    
    /// <summary>
    /// Interface para a tabela K_TRN_FINALIZARALUG_VITOR
    /// </summary>
    public partial interface IKTrnFinalizaralug : IEntityBase
    {
        
        /// <summary>
        /// Data devolucao (DATADEVOLUCAO.)
        /// Opcional = N, Invisível = False, Formato Data = Dia, Mês, Ano - Formato Hora = Hora, Minuto
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.1.0.20")]
        System.Nullable<System.DateTime> DataDevolucao
        {
            get;
            set;
        }
        
        /// <summary>
        /// Responsavel devolucao (RESPONSAVELDEVOLUCAO.)
        /// Opcional = N, Invisível = False, Tamanho = 100
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.1.0.20")]
        string ResponsavelDevolucao
        {
            get;
            set;
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.1.0.20")]
        Patrus.Transportes.Treinamento.Vitor.Entities.IVeiculo VeiculoInstance
        {
            get;
            set;
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.1.0.20")]
        Handle VeiculoHandle
        {
            get;
            set;
        }
    }
    
    /// <summary>
    /// Interface para o DAO para a tabela K_TRN_FINALIZARALUG_VITOR
    /// </summary>
    public partial interface IKTrnFinalizaralugDao : IBusinessEntityDao<IKTrnFinalizaralug>
    {
    }
    
    /// <summary>
    /// DAO para a tabela K_TRN_FINALIZARALUG_VITOR
    /// </summary>
    public partial class KTrnFinalizaralugDao : BusinessEntityDao<KTrnFinalizaralug, IKTrnFinalizaralug>, IKTrnFinalizaralugDao
    {
        
        public static KTrnFinalizaralugDao CreateInstance()
        {
            return CreateInstance<KTrnFinalizaralugDao>();
        }
    }
    
    /// <summary>
    /// KTrnFinalizaralug
    /// </summary>
    [EntityDefinitionName("K_TRN_FINALIZARALUG_VITOR")]
    [DataContract(Namespace = "http://Benner.Tecnologia.Common.DataContracts/2007/09", Name = "EntityBase")]
    public partial class KTrnFinalizaralug : BusinessEntity<KTrnFinalizaralug>, IKTrnFinalizaralug
    {
        
        /// <summary>
        /// Possui constantes para retornarem o nome dos campos definidos no Builder para cada propriedade
        /// </summary>
		public static class FieldNames
		{
			public const string DataDevolucao = "DATADEVOLUCAO";
			public const string ResponsavelDevolucao = "RESPONSAVELDEVOLUCAO";
			public const string Veiculo = "VEICULO";
		}

        
        /// <summary>
        /// Data devolucao (DATADEVOLUCAO.)
        /// Opcional = N, Invisível = False, Formato Data = Dia, Mês, Ano - Formato Hora = Hora, Minuto
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.1.0.20")]
        public System.Nullable<System.DateTime> DataDevolucao
        {
            get
            {
                return Fields["DATADEVOLUCAO"] as System.Nullable<System.DateTime>;
            }
            set
            {
                Fields["DATADEVOLUCAO"] = value;
            }
        }
        
        /// <summary>
        /// Responsavel devolucao (RESPONSAVELDEVOLUCAO.)
        /// Opcional = N, Invisível = False, Tamanho = 100
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.1.0.20")]
        public string ResponsavelDevolucao
        {
            get
            {
                return Fields["RESPONSAVELDEVOLUCAO"] as System.String;
            }
            set
            {
                Fields["RESPONSAVELDEVOLUCAO"] = value;
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.1.0.20")]
        public Patrus.Transportes.Treinamento.Vitor.Entities.IVeiculo VeiculoInstance
        {
            get
            {
                if (Veiculo.Handle == null)
                {
					return null;
                }
                return Veiculo.Instance;
            }
            set
            {
                if (value == null)
                {
					Veiculo = null;
					return;
                }
                Veiculo.Instance = (Patrus.Transportes.Treinamento.Vitor.Entities.Veiculo) value;
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.1.0.20")]
        public Handle VeiculoHandle
        {
            get
            {
                return Veiculo.Handle;
            }
            set
            {
                Veiculo.Handle = value;
            }
        }
        
        /// <summary>
        /// Veiculo (VEICULO.)
        /// Opcional = N, Invisível = False, Pesquisar = K_TRN_VITOR_VEICULOS
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.1.0.20")]
        public Benner.Tecnologia.Common.EntityAssociation<Patrus.Transportes.Treinamento.Vitor.Entities.Veiculo> Veiculo
        {
            get
            {
                return (Fields["VEICULO"] as EntityAssociation).Wrap<Patrus.Transportes.Treinamento.Vitor.Entities.Veiculo>(Patrus.Transportes.Treinamento.Vitor.Entities.Veiculo.Get);
            }
            set
            {
                if (value == null)
                {
                    this.Veiculo.Handle = null;
                }
                else
                {
                    if (value.Association.IsLoaded)
                    {
                        this.Veiculo.Instance = value.Instance;
                    }
                    else
                    {
                        this.Veiculo.Handle = value.Handle;
                    }
                }
            }
        }
    }
}
